### ISSUE TITLE
Find a better solution for appending gen. to Rails' generators

### ISSUE THREAD

**Issue by polarblau** [polarblau/spinaltap#11]
E.g. append `rails g vertebrae:model NAME` to `rails g model NAME`. Guessing rspec is doing something like that. Rails provides some hooks afaik.

Right now we're doing this: https://github.com/polarblau/vertebrae/commit/fac27e83b7a9434cf0ffef914ee09d78f868138a#diff-0

**Comment by polarblau** [comment]
I've been looking around for this (e.g. here: http://stackoverflow.com/questions/9214714/rails-hooking-into-orm-generator ). Any idea how to do this?

**Comment by pietia** [comment]
merging with #53
