### ISSUE TITLE
Alias generators namespace to `vb`

### ISSUE THREAD

**Issue by polarblau** [polarblau/spinaltap#14]

**Comment by polarblau** [comment]
It might be possible to add a second set of generators (maybe into the same files even) and extracting the functionality into modules used in both classes or then use `#invoke` to run the "real" generator.

**Comment by pietia** [comment]
yeah. i ended up with the same conclusion.

**Comment by polarblau** [comment]
Or then we just change the name อ_อ .

**Comment by pietia** [comment]
maybe we can rename all generators to 'vb' ?

**Comment by pietia** [comment]
it's easier to type 'vb' than 'verbarim' ;)

**Comment by polarblau** [comment]
That's true — still, maybe we should keep both _if_ we keep the name. Would be kind of weird to have the generators be called different than everything else.

**Comment by pietia** [comment]
let's wait then

**Comment by polarblau** [comment]
I'm torn about the name. I personally like it and I think the fact that it's rather complicated might be an advantage, but I see your point…

**Comment by pietia** [comment]
Closing. Let's focus on more important things :)
