### ISSUE TITLE
Implement testing against JS "fixture" files

### ISSUE THREAD

**Issue by polarblau** [polarblau/spinaltap#24]

**Comment by pietia** [comment]
ok, now we have `test/core` and `test/fixtures`. i think we need custom matcher: `assert_equal_fixture(relative_file_path, relative_fixture_path = nil)`

**Comment by polarblau** [comment]
+1 for the matcher .

**Comment by polarblau** [comment]
After you had mentioned it, I've played around with headless jasmine: https://github.com/polarblau/vertebrae/tree/headless_jasmine — Works okay so far. Haven't tried with .coffee files yet. — What do you think? Also about the folder structure?

**Comment by pietia** [comment]
@polarblau i have weird feeling that we should do some cleanup in dir structure :).

**Comment by pietia** [comment]
matchers ready

**Comment by polarblau** [comment]
>  i have weird feeling that we should do some cleanup in dir structure :)

— but why? :D

(+1 Yep, same here.)

**Comment by polarblau** [comment]
> matchers ready

Sweet, I'll have a look in a bit!

**Comment by pietia** [comment]
speaking about jasmine - i think we should have 2 types of test suits:
1) unit tests
2) integration tests

i think we should treat jasmine-based as integration ones

**Comment by polarblau** [comment]
I agree. Did you check the branch? Does that make sense to you?

**Comment by pietia** [comment]
it makes sens :) i think we should drop idea of using V8 or other
runtime, and use headless_jasmine toolkit

**Comment by polarblau** [comment]
dunno … you have looked into this more. :/ This was just easy to set up.

**Comment by polarblau** [comment]
Matchers look great. Now we got a real mess of files and folders there in the test dir :) . Could you explain `fixtures/models` vs `fixtures/assets/javascripts/models`? I'm not sure if I get all of this just yet.

**Comment by pietia** [comment]
commited some changes.
