### ISSUE TITLE
How can we test the generated Javascript?

### ISSUE THREAD

**Issue by polarblau** [polarblau/spinaltap#3]
Using e.g. jasmine and/or phantomjs? How to integrate test suits? How about Travis CI?

**Comment by pietia** [comment]
maybe we can utilize https://github.com/cowboyd/therubyracer somehow

**Comment by polarblau** [comment]
I think the tricky part is, to ensure that the mocks match the generated files at all times. Maybe we could use shared fixtures?

**Comment by pietia** [comment]
let's use fixtures
