### ISSUE TITLE
Check if manifest exists

### ISSUE THREAD

**Issue by polarblau** [polarblau/spinaltap#49]
Throw error/give warning if it doesn't.

**Comment by pietia** [comment]
`application.js` ? what if not ? create file?

**Comment by polarblau** [comment]
I guess then people aren't using the pipeline or a custom manifest and we just have to inform them about requiring "vertebrae" (only that one file).

**Comment by pietia** [comment]
yeah, just $std << "require app/ dir tree in your javascript code somewhere"

**Comment by polarblau** [comment]
I'm sure Thor has something like [warn_the_user_with_intense_colors](http://rubydoc.info/github/wycats/thor/master/Thor/Shell/Basic#say-instance_method) :) .
