### ISSUE TITLE
find better name!

### ISSUE THREAD

**Issue by pietia** [polarblau/spinaltap#55]
- spinal_tap

any other propositions?

**Comment by polarblau** [comment]
I could live with spinal tap. Anything speaking against it? Copyrights? Other gem? How do you feel about this suggestion?

**Comment by pietia** [comment]
ok, let's use spinal tap then :)

**Comment by polarblau** [comment]
You sure? Feeling comfortable with it? Any counter suggestions?

**Comment by pietia** [comment]
I have no better proposition :)
